docs(my-tmux): improve logging

diff --git a/bin/source_tmux_script b/bin/source_tmux_script
--- a/bin/source_tmux_script
+++ b/bin/source_tmux_script
@@ -1,5 +1,7 @@
 #!/bin/zsh
 
+set -e
+
 source_tmux_script() {
   if test "$1" = "-y"; then
     override_check="true"
@@ -7,7 +9,7 @@ source_tmux_script() {
   fi
 
   if test ! -d "$(dirname "$1")"; then
-    echo "Couldn't find folder containing $1" > /dev/stderr
+    echo "Couldn't find folder $(realpath "$(dirname $1)")" > /dev/stderr
     exit 0
   fi
 
