refactor(speeddial): put in local config

diff --git a/bin/tmux-speeddial b/bin/tmux-speeddial
--- a/bin/tmux-speeddial
+++ b/bin/tmux-speeddial
@@ -7,8 +7,14 @@ if test "$_line" = '0' ; then
  _line='10'
 fi
 
-file_name=$HOME/.tmux-speeddial
+mkdir -p "$LOCAL_CONFIG"
+file_name="$LOCAL_CONFIG/tmux-speeddial"
 session_name=$(head -"$_line" <"$file_name" | tail -1)
+
+if test -z "$session_name" ; then
+  echo "Entry $_line not found"
+  exit 1
+fi
 
 if ! (tmux list-sessions | ggrep -q "$session_name") ; then
   root_folder="$(echo "$session_name" | xargs zoxide query)"
